# Example Cloud Build configuration for Android app
# Demonstrates proper substitution handling and artifact management
#
# Usage:
#   gcloud builds submit . --config examples/cloudbuild-android-app.yaml \
#     --substitutions="_BUILD_TARGET=assembleRelease,_APP_DIR=android"

steps:
  # Step 1: Install dependencies
  # NOTE: Cloud Build runs from project root
  - name: '${_BUILDER_IMAGE}'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        cd ${_APP_DIR}
        npm ci

  # Step 2: Configure signing (fetch password from Secret Manager)
  # Keystore can be in repo or downloaded from GCS - both patterns shown
  - name: '${_BUILDER_IMAGE}'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        cd ${_APP_DIR}
        
        # Fetch keystore password from Secret Manager (if using GCP secrets)
        if [ -n "${_KEYSTORE_SECRET_NAME}" ]; then
          KEYSTORE_PASSWORD=$$(gcloud secrets versions access latest --secret=${_KEYSTORE_SECRET_NAME})
          printf '%s\n' \
            'MYAPP_RELEASE_STORE_FILE=${_KEYSTORE_FILE:-app-release.keystore}' \
            'MYAPP_RELEASE_KEY_ALIAS=${_KEY_ALIAS:-app-release-key}' \
            "MYAPP_RELEASE_STORE_PASSWORD=$$KEYSTORE_PASSWORD" \
            "MYAPP_RELEASE_KEY_PASSWORD=$$KEYSTORE_PASSWORD" >> android/gradle.properties
        fi
        
        # Download keystore from GCS if specified (optional, can also be in repo)
        if [ -n "${_KEYSTORE_GCS_PATH}" ]; then
          echo "Downloading keystore from GCS..."
          gsutil cp ${_KEYSTORE_GCS_PATH} android/app/${_KEYSTORE_FILE:-app-release.keystore} || \
            echo "Keystore not in GCS, using repo version if available"
        fi

  # Step 3: Build Android app
  # NOTE: Cloud Build runs from project root, so cd into android/ subdirectory
  # OPTIMIZED: Uses parallel execution, build caching, and increased workers
  - name: '${_BUILDER_IMAGE}'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        cd ${_APP_DIR}/android

        # Handle Cloud Build substitution properly
        GRADLE_TASK="${_BUILD_TARGET}"
        if [ -z "$$GRADLE_TASK" ]; then
          GRADLE_TASK="assembleRelease"
        fi

        echo "Building with task: $$GRADLE_TASK"

        # Use optimized GRADLE_OPTS (6GB heap, increased metaspace)
        GRADLE_OPTS="${_GRADLE_OPTS}"
        if [ -z "$$GRADLE_OPTS" ]; then
          GRADLE_OPTS="-Xmx6144m -XX:MaxMetaspaceSize=2048m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC"
        fi

        export GRADLE_OPTS

        # Optimized build with parallel execution and caching
        # Adjust --max-workers based on Cloud Build machine type
        # N1_HIGHCPU_8: use 6-8 workers
        # N1_HIGHCPU_32: use 16-24 workers
        ./gradlew $$GRADLE_TASK \
          --parallel \
          --max-workers=${_MAX_WORKERS} \
          --build-cache \
          --stacktrace \
          ${_GRADLE_EXTRA_FLAGS}

  # Step 4: Find and verify artifacts
  # NOTE: Step 3 ran from android/, artifacts are at app/build/outputs/ relative to android/
  # From project root, they're at ${_APP_DIR}/android/app/build/outputs/
  - name: '${_BUILDER_IMAGE}'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        cd ${_APP_DIR}
        artifact-finder.sh . all

  # Step 5: Upload artifacts to GCS
  # NOTE: Cloud Build runs from project root, Step 3 ran from android/, artifacts are at android/app/build/...
  - name: '${_BUILDER_IMAGE}'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        # Determine artifact path based on build target
        if [ "${_BUILD_TARGET}" = "bundleRelease" ]; then
          ARTIFACT_PATH="${_APP_DIR}/android/app/build/outputs/bundle/release/app-release.aab"
          ARTIFACT_NAME="app-release-${BUILD_ID}.aab"
        else
          ARTIFACT_PATH="${_APP_DIR}/android/app/build/outputs/apk/release/app-release.apk"
          ARTIFACT_NAME="app-release-${BUILD_ID}.apk"
        fi
        
        # Check if artifact exists
        if [ ! -f "$$ARTIFACT_PATH" ]; then
          echo "Error: Could not find artifact at $$ARTIFACT_PATH"
          echo "Searching for artifacts..."
          find . -name "app-release.*" -type f 2>/dev/null | head -10 || true
          exit 1
        fi
        
        GCS_BUCKET="${_GCS_BUCKET}"
        if [ -z "$$GCS_BUCKET" ]; then
          echo "Error: _GCS_BUCKET must be set"
          exit 1
        fi
        
        echo "Found artifact at: $$ARTIFACT_PATH"
        echo "Uploading to gs://$$GCS_BUCKET/builds/$$ARTIFACT_NAME"
        gsutil cp "$$ARTIFACT_PATH" "gs://$$GCS_BUCKET/builds/$$ARTIFACT_NAME"
    waitFor: ['-']

# Substitutions (with proper defaults)
substitutions:
  _BUILDER_IMAGE: 'us-central1-docker.pkg.dev/${PROJECT_ID}/android-build-images/android-build-image:latest'
  _BUILD_TARGET: 'assembleRelease'  # assembleRelease, assembleDebug, bundleRelease, bundleDebug
  _APP_DIR: 'app'  # Directory containing Android project (e.g., 'app' for Expo projects)

  # Performance optimizations (NEW)
  _GRADLE_OPTS: '-Xmx6144m -XX:MaxMetaspaceSize=2048m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC'  # Optimized for 6GB heap
  _MAX_WORKERS: '8'  # Adjust based on machine type: N1_HIGHCPU_8=6-8, N1_HIGHCPU_32=16-24
  _GRADLE_EXTRA_FLAGS: ''  # Extra Gradle flags (e.g., '--no-daemon' for clean builds)

  _GCS_BUCKET: ''  # GCS bucket for artifacts (required)

  # Keystore configuration (all optional - keystore can be in repo or GCS)
  _KEYSTORE_SECRET_NAME: ''  # Secret Manager secret name for keystore password (optional)
  _KEYSTORE_GCS_PATH: ''  # GCS path to keystore file, e.g., 'gs://bucket/keystore.jks' (optional)
  _KEYSTORE_FILE: 'app-release.keystore'  # Keystore filename (default: app-release.keystore)
  _KEY_ALIAS: 'app-release-key'  # Key alias (default: app-release-key)

# Options - OPTIMIZED for better performance
options:
  machineType: 'N1_HIGHCPU_32'  # Upgraded from N1_HIGHCPU_8 for faster parallel builds
  logging: CLOUD_LOGGING_ONLY
  diskSizeGb: 200  # Increased from 100GB for better caching

# Timeout
timeout: '1800s'

